app_name: Bookingz
copyright_message: Copyright Craft Academy Labs © 2016
available_locales: ['sv', 'en']
default_locale: en
# Available modes: 'daily_view' & 'weekly_view'
mode: :daily_view
#mode: :weekly_view
slot_configuration:
  #increment: 270 # In minutes
  increment: 60 # In minutes
  start_time: 6 # In hours from midnight
  #end_time: 16 # In hours from midnight
  end_time: 23 # In hours from midnight